language: ruby
  global:
  - NODE_ENV=test
  - PGPORT=5433
  - PGHOST=localhost
services:
  - postgresql
addons:
   sources:
    - precise-pgdg-11.4
    packages:
    - postgresql-11.4
    - postgresql-contrib-11.4
  postgresql: '11.4'
  code_climate:
    repo_token:
      secure: 'bw2ZmPONB9aifYI9aP6AVuui+3WbHgaTkY6Bbnt64uKUzsnMrmnXh0K0deEbuScW3ajHjaaCN8EA3ppxyLV1vnxBporS6+gzCu+GRByOt9vTv0M1m5x9KnKnVQWOkW9YWC+ynvdjHLQOLF+dRzO7yBtGHh6dGVuIfExa1Yb0m6wSSTS8InsrIIixGJqtEhx85xw7VTMe64fV7RUZ0NieECLo9z4r5vnD6aO7eKEaTwNX9fryM8ytk7PWRAlBea6wJ2I+EyzGNx8kX/Lpi7525ySIlcewEuvwAr1EbStM41DINbIp2jWdHGcSIpBDnbF0Gm9FPXKbYtyh9hQwSUjX62WJ4t/X48irKXWbpGB5MlCrIDejedk57AxPNRRnns7QX9iND+oAI6wfvdHPM/yv9zE/lLerm6/kesY7PLvIW1em8jbPLR+rUvFqxmDVoxyZOpBidxEsHPheoO5R9lkIqsVJgf98zGuy4E2fC7qkcjK56BWcKvBi5qpTWFPcotKnVekaTo+7dhdFN+3SkECe3neokVJXk0tkGKTI9Siax4J2Qcdrva1nLxIufS/Og8JuEKkIMNhAfm8gNBpFJ1cDIlDjTI02fliR9DPTt6nTj/PkUcNDTiK/nCxsdMy3qww/p/pw/wLHkazbMW+j6XbwF5TlPQADvKm/4S8Z19HGmsQ='

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c 'create database "iRep_test";'
  - psql -U postgres iRep_test -c 'create extension "uuid-ossp";'
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
